### ISSUE TITLE
NoClassDefFoundError on Sign Closing

### ISSUE THREAD

**Issue by rihlsul** [Buam/ultimatesigns#5]
Heya!

Using UltimateSigns v1.6.0 in a 1.15.2 CraftBukkit server (full version below).

With US installed, when I place a sign, I can edit the text of the sign, but as soon as I close the sign edit UI, the player is immediately disconnected from the server.  I've cloned my server, set it up with only ProtocolLib 4.4.0 and Ultimate Signs v1.6.0, as well as trying out ProtocolLib 4.5.0.

The error is simply:
`Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer`

Full log is here, but it's not even giving a trace on that error, so not sure what to do with it:
https://pastebin.com/k7BgD5zN

**Comment by Buam** [comment]
Hey!
Looks like this is an issue with ProtocolLib. Unfortunately, the error is basically not visible in the trace, since it only shows the Error itself, not what caused it.
I also don't have any time to continue development on US, so it is discontinued for now.
I've thought about making a version that only contains the sign editor, as that is the feature many people are downloading this plugin for.
I'm sorry that you can't use the plugin :/

**Comment by rihlsul** [comment]
That's sad, but I know how it is not to have time.
